---
- mrlesmithjr.squid
- stackhpc.monasca_default_alarms
- stackhpc.grubcmdline
- name: wazuh-ansible
  src: https://github.com/wazuh/wazuh-ansible.git
  version: v4.1.5
- src: geerlingguy.swap
  version: 1.0.2
